#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="${1:-mobile-sdk-release-evidence}"
EVIDENCE_DIR="${2:-}"
REQUIRE_MOBILE_EVIDENCE="${GPUF_REQUIRE_MOBILE_EVIDENCE:-0}"

mkdir -p "$OUT_DIR"
rm -f \
  "$OUT_DIR/mobile-release-gate-status.txt" \
  "$OUT_DIR/mobile-evidence-status.txt" \
  "$OUT_DIR/mobile-source-sensitive-grep.txt" \
  "$OUT_DIR/mobile-toolchain-status.txt" \
  "$OUT_DIR/mobile-sdk-symbols.txt" \
  "$OUT_DIR/README.md"

is_truthy() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

fail_gate() {
  local message="$1"
  echo "$message" >"$OUT_DIR/mobile-release-gate-status.txt"
  printf 'mobile SDK release gate failed: %s\n' "$message" >&2
  exit 1
}

redact_local_path() {
  local value="$1"
  local repo_root="${PWD%/}"
  local home_dir="${HOME:-}"

  value="${value//$repo_root/<repo>}"
  if [[ -n "$home_dir" ]]; then
    value="${value//$home_dir/<home>}"
  fi
  printf '%s\n' "$value"
}

status_is_blocking() {
  local status_upper
  status_upper="$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')"

  case "$status_upper" in
    *FAIL*|*MISSING*|*INCOMPLETE*|*PENDING*|*REQUIRED*|*REQUIRES*|*REQUIRE_*|*FOLLOWUP*|*ACTION*|*CONDITIONAL*|*NOT_RERUN*|*PLACEHOLDER*|*TODO*|*TBD*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

read_evidence_status() {
  local evidence_file="$1"
  local status
  status="$(sed -n 's/^status:[[:space:]]*//p' "$evidence_file" | sed -n '1p')"
  if [[ -z "$status" ]]; then
    status="<missing status>"
  fi
  printf '%s\n' "$status"
}

{
  echo "generated_at_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "repo=<repo>"
  echo "GPUF_REQUIRE_MOBILE_EVIDENCE=$REQUIRE_MOBILE_EVIDENCE"
  echo "evidence_dir=$(redact_local_path "${EVIDENCE_DIR:-<unset>}")"
  git rev-parse HEAD 2>/dev/null | sed 's/^/git_head=/' || true
} >"$OUT_DIR/mobile-release-context.txt"

mobile_sources=(
  gpuf-c/src/lib.rs
  gpuf-c/src/jni_remote_worker.rs
  gpuf-c/src/handle/android_sdk.rs
  gpuf-c/src/handle/worker_sdk.rs
  gpuf-c/examples/android_test.c
  gpuf-c/examples/ios_sim_test/GPUFIosSimTest/ContentView.swift
)

if command -v rg >/dev/null 2>&1; then
  if rg -n --glob '!**/DerivedData/**' \
    '8[.]140[.]251[.]142|hf_[[:alnum:]]{20,}|BEGIN[[:space:]].*PRIVATE[[:space:]]KEY|sshpass[[:space:]]+-p|SharedPreferences|UserDefaults|NSUserDefaults|MODE_PRIVATE|putString\([^)]*(token|password|secret)|setValue\([^)]*(token|password|secret)' \
    "${mobile_sources[@]}" >"$OUT_DIR/mobile-source-sensitive-grep.txt" 2>&1; then
    fail_gate "mobile source sensitive-pattern grep found forbidden matches"
  fi
else
  echo "rg not available; mobile source sensitive grep not run" >"$OUT_DIR/mobile-source-sensitive-grep.txt"
fi

{
  echo "adb=$(command -v adb || true)"
  echo "xcodebuild=$(command -v xcodebuild || true)"
  echo "cargo-ndk=$(command -v cargo-ndk || true)"
  echo "llvm-symbolizer=$(command -v llvm-symbolizer || true)"
} >"$OUT_DIR/mobile-toolchain-status.txt"

if command -v rg >/dev/null 2>&1; then
  rg -n 'start_remote_worker|Java_com_gpuf_c_RemoteWorker_startRemoteWorker|control_tls|serverAddr' \
    gpuf-c/gpuf_c.h gpuf-c/src/lib.rs gpuf-c/src/jni_remote_worker.rs \
    docs/mobile-sdk gpuf-c/docs/mobile gpuf-c/docs/JNI_RemoteWorker_API_CN.md \
    >"$OUT_DIR/mobile-sdk-symbols.txt" 2>&1 || true
fi

required_files=(
  android-target-compile.txt
  ios-target-compile.txt
  android-keystore-review.txt
  ios-keychain-review.txt
  mobile-control-tls-pinning.txt
  android-instrumentation.txt
  ios-simulator-device.txt
  asan-tsan.txt
  permissions-logging-audit.txt
)

missing=0
blocking=0
{
  if [[ -z "$EVIDENCE_DIR" ]]; then
    echo "missing evidence directory"
    missing=1
  elif [[ ! -d "$EVIDENCE_DIR" ]]; then
    echo "evidence directory does not exist: $EVIDENCE_DIR"
    missing=1
  else
    for required in "${required_files[@]}"; do
      if [[ -s "$EVIDENCE_DIR/$required" ]]; then
        status="$(read_evidence_status "$EVIDENCE_DIR/$required")"
        echo "present: $required status=$status"
        if [[ "$status" == "<missing status>" ]]; then
          echo "blocking-status: $required is missing a status header"
          blocking=1
        elif status_is_blocking "$status"; then
          echo "blocking-status: $required status=$status"
          blocking=1
        fi
      else
        echo "missing: $required"
        missing=1
      fi
    done
  fi
} >"$OUT_DIR/mobile-evidence-status.txt"

if is_truthy "$REQUIRE_MOBILE_EVIDENCE" && { [[ "$missing" -ne 0 ]] || [[ "$blocking" -ne 0 ]]; }; then
  fail_gate "GPUF_REQUIRE_MOBILE_EVIDENCE is set but required mobile evidence is missing or has blocking status"
fi

cat >"$OUT_DIR/README.md" <<EOF
# GPUFabric Mobile SDK Release Gate Evidence

Generated by \`scripts/mobile_sdk_release_gate.sh\`.

Default CI mode records mobile release gate status. Formal mobile SDK release jobs must set \`GPUF_REQUIRE_MOBILE_EVIDENCE=1\` and pass an evidence directory containing non-empty files with non-blocking \`status:\` headers:

- \`android-target-compile.txt\`
- \`ios-target-compile.txt\`
- \`android-keystore-review.txt\`
- \`ios-keychain-review.txt\`
- \`mobile-control-tls-pinning.txt\`
- \`android-instrumentation.txt\`
- \`ios-simulator-device.txt\`
- \`asan-tsan.txt\`
- \`permissions-logging-audit.txt\`

Files in this bundle:

- \`mobile-release-context.txt\`: git and gate context.
- \`mobile-source-sensitive-grep.txt\`: forbidden mobile source-pattern grep output; any match fails the gate.
- \`mobile-toolchain-status.txt\`: local availability of Android/iOS diagnostic tools.
- \`mobile-sdk-symbols.txt\`: SDK compatibility and control TLS reference search.
- \`mobile-evidence-status.txt\`: required release evidence presence and status check. Strict mode fails on missing evidence, missing \`status:\` headers, or blocking status markers such as \`REQUIRED\`, \`REQUIRES\`, \`PENDING\`, \`FOLLOWUP\`, \`ACTION\`, \`CONDITIONAL\`, \`NOT_RERUN\`, \`MISSING\`, \`INCOMPLETE\`, \`TODO\`, or \`TBD\`.
- \`mobile-release-gate-status.txt\`: present only when a required gate failed.
EOF

printf 'mobile SDK release gate evidence written to %s\n' "$OUT_DIR"
